name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build documentation site
        run: npm run build
        env:
          # Optional: set in GitHub Variables to point to your Worker if not routed under /api
          VITE_AUTORAG_API_BASE: ${{ vars.AUTORAG_API_BASE }}

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: obsidian-developer-docs
          directory: en/.vitepress/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          deploymentName: Production

  deploy-worker:
    runs-on: ubuntu-latest
    needs: deploy
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Worker dependencies
        working-directory: ./workers/autorag-api
        run: npm ci

      - name: Deploy Worker
        working-directory: ./workers/autorag-api
        run: npx wrangler deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  ingest-docs:
    runs-on: ubuntu-latest
    needs: [deploy, deploy-worker]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Ingest documentation into AutoRAG via Worker
        run: npm run ingest
        env:
          # Prefer vars.AUTORAG_API_BASE if your Worker isn’t routed under /api
          WORKER_URL: ${{ vars.AUTORAG_API_BASE }}
          INGESTION_TOKEN: ${{ secrets.INGESTION_TOKEN }}

  sync-autorag:
    runs-on: ubuntu-latest
    needs: [deploy, deploy-worker, ingest-docs]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
      - name: Trigger AutoRAG Sync
        run: |
          curl -X POST \
            https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/autorag/rags/${{ secrets.AUTORAG_NAME }}/sync \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json"
